name: pdf_viewer_jk
description: A flutter plugin for viewing PDF files in mobile app (Android & iOS).
version: 2.1.5
repository: https://github.com/jawadsahil/pdf_viewer_jk
homepage: https://jawad.pro

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.8.2
  flutter_cache_manager: ^3.1.2
  flutter_spinbox: ^0.5.4
  flutter_svg: ^1.0.0
  http: ^0.13.3
  path_provider: ^2.0.2
  path: ^1.8.0
  pool: ^1.5.0

flutter:
  plugin:
    platforms:
      android:
        package: pro.jawad.pdf_viewer_jk
        pluginClass: PdfViewerJkPlugin
      ios:
        pluginClass: PdfViewerJkPlugin
